
modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory

license="${mod_license}"
issueTrackerURL="https://discord.gg/2VayYKktvx" #optional


[[mods]] #mandatory

modId="${mod_id}" #mandatory
version="${mod_version}" #mandatory

displayName="${mod_name}" #mandatory
updateJSONURL="https://curseupdate.com/1314549/endermanmahjong?ml=neoforge" #optional
displayURL="https://legacy.curseforge.com/minecraft/mc-mods/considerate-endermen" #optional
authors="${mod_authors}" #optional
description='''${mod_description}'''













[[dependencies.${mod_id}]] #optional
    # the modid of the dependency
    modId="neoforge" #mandatory
    # The type of the dependency. Can be one of "required", "optional", "incompatible" or "discouraged" (case insensitive).
    # 'required' requires the mod to exist, 'optional' does not
    # 'incompatible' will prevent the game from loading when the mod exists, and 'discouraged' will show a warning
    type="required" #mandatory
    # Optional field describing why the dependency is required or why it is incompatible
    # reason="..."
    # The version range of the dependency
    versionRange="${neo_version_range}" #mandatory
    # An ordering relationship for the dependency.
    # BEFORE - This mod is loaded BEFORE the dependency
    # AFTER - This mod is loaded AFTER the dependency
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT, or SERVER
    side="BOTH"


[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    # This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"







[[mixins]]
    config="mixins.mahjong.json"
